server:
  port: '8081'
  shutdown: graceful

application:
  kafka:
    topic: ORDERS_ENRICHED
    bootstrap-servers: broker-1:9092,broker-2:9092,broker-3:9092
    isolation-level: read_uncommitted
    enable-auto-commit: false
    partitionCount: 4
    replicaCount: 3
  redis:
    expire-duration-millis: 60000

spring:
  profiles:
    active: redis
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db/changelog/db.changelog-server.xml
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      password: mypass
      timeout: 60000
      client-type: lettuce
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: spring-consumer-group

logging:
  config: /opt/local/spring-consumer/config/log4j2-docker.xml