server:
  port: '8081'
  shutdown: graceful

application:
  kafka:
    topic: ORDERS_ENRICHED
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    partitionCount: 4
    replicaCount: 3

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: "spring-consumer-group"