server:
  port: '8081'
  shutdown: graceful

application:
  kafka:
    topic: ORDERS_ENRICHED
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    partitionCount: 4
    replicaCount: 3
  redis:
    expire-duration-millis: 300000

spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      password: mypass
      timeout: 60000
      client-type: lettuce
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: "spring-consumer-group"

#logging:
#  config: "config/log4j2.xml"