FROM node:16-bullseye-slim

WORKDIR /usr/src/ganache

RUN npm install -g ganache-cli

EXPOSE 8545

CMD ["ganache-cli", "-m", "bargain olive carry essence inner slogan harsh special enact short lady immune", -]
