version: '3.7'

networks:
  default:
    external: true
    name: kafka-local

services:
  ganache:
    build: .
    ports:
      - "8545:8545"
    command: ganache-cli -h 0.0.0.0
    volumes:
      - ./db:/db
