version: "3.7"

networks:
  default:
    external: true
    name: kafka-local

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - ./data:/root/redis
      - ./conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=mypass
      - REDIS_PORT=6379

  spring-consumer:
    container_name: spring-consumer
    image: spring-consumer:latest
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=docker
        -Dspring.config.location=/opt/local/spring-consumer/config/application-docker.yml
    volumes:
      - ./configs:/opt/local/spring-consumer/config
      - ./log:/opt/local/spring-consumer/log
    depends_on:
      - redis
      - postgres
