version: "3.7"

networks:
  default:
    external: true
    name: kafka-local

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - ./pgadmin:/opt/local/pgadmin4
    environment:
      - PGADMIN_SERVER_JSON_FILE=/opt/local/pgadmin4/servers.json
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command:
      - '--maxmemory 256mb'
    ports:
      - "6379:6379"
    volumes:
      - ./data:/root/redis
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=mypass
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 512M

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:alpine
    ports:
      - "9121:9121"
    restart: unless-stopped
    command:
      - '--redis.addr=redis://redis:6379'
      - '-include-system-metrics=true'
    depends_on:
      - redis

  spring-consumer-redis:
    image: spring-consumer:latest
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=redis
        -Dspring.config.location=/opt/local/spring-consumer/config/application-docker-redis.yml
    volumes:
      - ./configs:/opt/local/spring-consumer/config
      - ./log:/opt/local/spring-consumer/log
    depends_on:
      - redis
      - postgres

  spring-consumer-eos:
    image: spring-consumer:latest
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=eos
        -Dspring.config.location=/opt/local/spring-consumer/config/application-docker-eos.yml
    volumes:
      - ./configs:/opt/local/spring-consumer/config
      - ./log:/opt/local/spring-consumer/log
    depends_on:
      - postgres
