SELECT ORDER_ID, COUNT(COUNT) AS COUNT, SUM(COUNT) AS SUM_COUNT
FROM orders
    WINDOW TUMBLING (SIZE 1 DAY)
WHERE ROWTIME >= UNIX_TIMESTAMP() - 86400000 -- 1 day in milliseconds
GROUP BY ORDER_ID
HAVING COUNT(COUNT) > 1;
